from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Query planning
# ---------------------------------------------------------------------------


class ExecutionMode(StrEnum):
    """
    Determines which evidence path is required to answer a question.

    RETRIEVAL:
        PDF/TXT/document-text semantic retrieval.

    STRUCTURED:
        CSV/Excel analysis against the complete dataset.

    HYBRID:
        Both textual retrieval and structured-data analysis are required.
    """

    RETRIEVAL = "retrieval"
    STRUCTURED = "structured"
    HYBRID = "hybrid"


class QueryPlan(BaseModel):
    """
    High-level query plan.

    IMPORTANT:
    This model intentionally does NOT contain operations such as:
        sum, average, groupby, rank, yoy, percentage_change, etc.

    The planner decides what evidence is needed. The structured-analysis
    engine decides how to compute the requested answer dynamically.
    """

    mode: ExecutionMode = ExecutionMode.RETRIEVAL

    is_follow_up: bool = False
    out_of_scope: bool = False
    ambiguous: bool = False
    ambiguity_reason: str | None = None

    # Documents selected by the planner.
    document_ids: list[str] = Field(default_factory=list)
    document_hints: list[str] = Field(default_factory=list)

    # Query used for semantic retrieval from PDF/TXT/document chunks.
    retrieval_query: str | None = None

    # Natural-language analytical task sent to the structured engine.
    structured_question: str | None = None

    # Context extracted by the planner. These are useful for conversation
    # continuity and final answer generation, but they do NOT constrain
    # what analysis the system is capable of performing.
    entities: list[str] = Field(default_factory=list)
    metrics: list[str] = Field(default_factory=list)
    years: list[int] = Field(default_factory=list)
    filters: dict[str, Any] = Field(default_factory=dict)

    @field_validator("document_ids", "document_hints", "entities", "metrics")
    @classmethod
    def clean_string_lists(cls, values: list[str]) -> list[str]:
        result: list[str] = []
        seen: set[str] = set()

        for value in values:
            value = str(value).strip()
            if not value:
                continue

            key = value.casefold()
            if key in seen:
                continue

            seen.add(key)
            result.append(value)

        return result

    @field_validator("years")
    @classmethod
    def clean_years(cls, values: list[int]) -> list[int]:
        result: list[int] = []

        for value in values:
            try:
                year = int(value)
            except (TypeError, ValueError):
                continue

            if 1000 <= year <= 9999 and year not in result:
                result.append(year)

        return result


# ---------------------------------------------------------------------------
# Dataset schema models
# ---------------------------------------------------------------------------


class ColumnSchema(BaseModel):
    """
    Schema information exposed to the LLM for structured-data reasoning.
    """

    name: str
    dtype: str

    nullable: bool = False
    null_count: int = 0
    unique_count: int | None = None

    sample_values: list[Any] = Field(default_factory=list)

    minimum: Any | None = None
    maximum: Any | None = None


class DatasetSchema(BaseModel):
    """
    Description of one registered CSV/Excel dataset.
    """

    document_id: str
    filename: str

    # Safe internal DuckDB table name such as dataset_1.
    table_name: str

    row_count: int
    column_count: int

    columns: list[ColumnSchema] = Field(default_factory=list)


class DatasetInfo(BaseModel):
    """
    Lightweight dataset metadata used by the structured executor.
    """

    document_id: str
    filename: str
    table_name: str
    row_count: int
    column_count: int


# ---------------------------------------------------------------------------
# Generated structured analysis
# ---------------------------------------------------------------------------


class GeneratedQuery(BaseModel):
    """
    SQL generated by Gemini for structured-data analysis.

    SQL is never trusted directly. sql_executor.py validates it before
    DuckDB is allowed to execute it.
    """

    sql: str

    explanation: str = ""

    tables_used: list[str] = Field(default_factory=list)
    columns_used: list[str] = Field(default_factory=list)

    @field_validator("sql")
    @classmethod
    def sql_must_not_be_empty(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("Generated SQL cannot be empty.")

        return value


class StructuredResult(BaseModel):
    """
    Verified result returned by DuckDB.

    This becomes grounded evidence for the final answer model.
    """

    sql: str

    columns: list[str] = Field(default_factory=list)
    rows: list[dict[str, Any]] = Field(default_factory=list)

    row_count: int = 0
    truncated: bool = False

    source_document_ids: list[str] = Field(default_factory=list)
    source_filenames: list[str] = Field(default_factory=list)

    explanation: str = ""

    # Human-readable representation passed to the final answering model.
    result_text: str = ""


class AnalysisResult(BaseModel):
    """
    Generic analysis evidence.

    This replaces the old operation-specific AnalysisResult design.

    There is deliberately no assumption that the result came from a
    predefined operation such as SUM, AVG, GROUP BY, YOY, etc.
    """

    operation: str = "dynamic_sql"

    value: Any | None = None

    table: list[dict[str, Any]] = Field(default_factory=list)
    columns: list[str] = Field(default_factory=list)

    formula: str | None = None
    query: str | None = None

    filename: str = ""
    document_id: str = ""

    source_filenames: list[str] = Field(default_factory=list)
    source_document_ids: list[str] = Field(default_factory=list)

    rows_used: int | None = None
    truncated: bool = False

    explanation: str = ""


# ---------------------------------------------------------------------------
# Retrieved document evidence
# ---------------------------------------------------------------------------


class Evidence(BaseModel):
    document_id: str
    filename: str
    document_type: str

    chunk_id: str
    text: str

    similarity: float = 0.0

    page_number: int = 0
    section: str = ""

    source_reference: str = ""

    start_line: int = 0
    end_line: int = 0

    row_start: int = 0
    row_end: int = 0

    columns: str = ""
    entities: str = ""
    year: int = 0


# ---------------------------------------------------------------------------
# Sources returned to frontend
# ---------------------------------------------------------------------------


class Source(BaseModel):
    document_id: str = ""
    filename: str = ""

    source_reference: str = ""
    excerpt: str = ""

    document_type: str = ""

    page_number: int = 0
    section: str = ""

    row_start: int = 0
    row_end: int = 0

    # Structured analysis provenance.
    operation: str | None = None
    formula: str | None = None
    value: Any | None = None


# ---------------------------------------------------------------------------
# Conflict detection
# ---------------------------------------------------------------------------


class NumericClaim(BaseModel):
    metric: str

    value: float

    entity: str = ""
    year: int = 0
    unit: str = ""

    filename: str = ""
    document_id: str = ""

    source_reference: str = ""


class ConflictItem(BaseModel):
    metric: str

    entity: str = ""
    year: int = 0
    unit: str = ""

    claims: list[NumericClaim] = Field(default_factory=list)


class ConflictReport(BaseModel):
    has_conflicts: bool = False
    conflicts: list[ConflictItem] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Conversation state
# ---------------------------------------------------------------------------


class ConversationContext(BaseModel):
    """
    Lightweight context used for follow-up questions.

    It stores useful references from previous turns without locking the
    next question into a predefined analytical operation.
    """

    entities: list[str] = Field(default_factory=list)
    metrics: list[str] = Field(default_factory=list)
    years: list[int] = Field(default_factory=list)

    document_ids: list[str] = Field(default_factory=list)
    document_hints: list[str] = Field(default_factory=list)

    last_question: str | None = None
    last_answer: str | None = None

    last_execution_mode: ExecutionMode | None = None

    # Useful structured values from the previous turn.
    numeric_results: dict[str, float] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# API models
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    question: str = Field(min_length=1)
    conversation_id: str | None = None

    @field_validator("question")
    @classmethod
    def clean_question(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("Question cannot be empty.")

        return value


class ChatResponse(BaseModel):
    conversation_id: str

    answer: str

    status: Literal[
        "answered",
        "missing",
        "out_of_scope",
        "ambiguous",
        "conflict",
        "error",
    ] = "answered"

    sources: list[Source] = Field(default_factory=list)

    execution_flow: list[str] = Field(default_factory=list)

    query_plan: QueryPlan | None = None


class DocumentResponse(BaseModel):
    document_id: str
    filename: str
    file_type: str
    status: str

    chunk_count: int = 0
    page_count: int | None = None

    created_at: str | None = None


class UploadResponse(BaseModel):
    document_id: str
    filename: str
    file_type: str
    status: str

    chunk_count: int = 0
    page_count: int | None = None


class DeleteResponse(BaseModel):
    document_id: str
    deleted: bool = True


class ConversationMessage(BaseModel):
    id: str
    conversation_id: str

    role: Literal["user", "assistant"]
    content: str

    status: str | None = None

    sources: list[Source] = Field(default_factory=list)
    execution_flow: list[str] = Field(default_factory=list)

    query_plan: QueryPlan | None = None

    created_at: str


class ConversationResponse(BaseModel):
    conversation_id: str
    context: ConversationContext

    messages: list[ConversationMessage] = Field(default_factory=list)
